api_platform:
    mapping:
        paths: 
            - '%kernel.project_dir%/src/Entity' # default configuration for annotations
    title: 'API Gamaliel App'
    collection:
        pagination:
            enabled: true
