doctrine:
    dbal:
        url: '%env(resolve:DATABASE_URL)%'

        # IMPORTANT: You MUST configure your server version,
        # either here or in the DATABASE_URL env var (see .env file)
        #server_version: '15'
    orm:
        auto_generate_proxy_classes: true
        enable_lazy_ghost_objects: true
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        auto_mapping: true
        mappings:
            App:
                is_bundle: false
                dir: '%kernel.project_dir%/src/Entity'
                prefix: 'App\Entity'
                alias: App
        dql:
            datetime_functions:
                second: DoctrineExtensions\Query\Sqlite\Second
                minute: DoctrineExtensions\Query\Sqlite\Minute
                hour: DoctrineExtensions\Query\Sqlite\Hour
                day: DoctrineExtensions\Query\Sqlite\Day
                dayname: DoctrineExtensions\Query\Sqlite\DayName
                #monthname: DoctrineExtensions\Query\Sqlite\MonthName
                month: DoctrineExtensions\Query\Sqlite\Month
                week: DoctrineExtensions\Query\Sqlite\Week
                weekday: DoctrineExtensions\Query\Sqlite\WeekDay
                year: DoctrineExtensions\Query\Sqlite\Year
                date: DoctrineExtensions\Query\Sqlite\Date
                date_format: DoctrineExtensions\Query\Sqlite\DateFormat
                dateadd: DoctrineExtensions\Query\Sqlite\DateAdd
                datediff: DoctrineExtensions\Query\Sqlite\DateDiff
                julianday: DoctrineExtensions\Query\Sqlite\JulianDay
                strftime: DoctrineExtensions\Query\Sqlite\StrfTime
                #strtodate: DoctrineExtensions\Query\Sqlite\StrToDate
                #time: DoctrineExtensions\Query\Sqlite\Time
                #timestampadd: DoctrineExtensions\Query\Sqlite\TimestampAdd
                #timestampdiff: DoctrineExtensions\Query\Sqlite\TimestampDiff
when@test:
    doctrine:
        dbal:
            # "TEST_TOKEN" is typically set by ParaTest
            dbname_suffix: '_test%env(default::TEST_TOKEN)%'

when@prod:
    doctrine:
        orm:
            auto_generate_proxy_classes: false
            proxy_dir: '%kernel.build_dir%/doctrine/orm/Proxies'
            query_cache_driver:
                type: pool
                pool: doctrine.system_cache_pool
            result_cache_driver:
                type: pool
                pool: doctrine.result_cache_pool

    framework:
        cache:
            pools:
                doctrine.result_cache_pool:
                    adapter: cache.app
                doctrine.system_cache_pool:
                    adapter: cache.system
