<?php

namespace ContainerGKpBONF;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_Wri7zfVService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.wri7zfV' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.wri7zfV'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'fonction' => ['privates', 'App\\Entity\\Fonction', 'getFonctionService', true],
            'paginator' => ['services', 'knp_paginator', 'getKnpPaginatorService', true],
        ], [
            'fonction' => 'App\\Entity\\Fonction',
            'paginator' => '?',
        ]);
    }
}
