<?php

namespace ContainerGKpBONF;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_JWtC6gJService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.JWtC6gJ' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.JWtC6gJ'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'agent' => ['privates', 'App\\Entity\\Agent', 'getAgentService', true],
            'paginator' => ['services', 'knp_paginator', 'getKnpPaginatorService', true],
            'repoAgent' => ['privates', 'App\\Repository\\AgentRepository', 'getAgentRepositoryService', true],
            'repoPaie' => ['privates', 'App\\Repository\\PaiementRepository', 'getPaiementRepositoryService', true],
        ], [
            'agent' => 'App\\Entity\\Agent',
            'paginator' => '?',
            'repoAgent' => 'App\\Repository\\AgentRepository',
            'repoPaie' => 'App\\Repository\\PaiementRepository',
        ]);
    }
}
