<?php

namespace ContainerGKpBONF;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_FX_XS9zService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.fX.XS9z' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.fX.XS9z'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'fonction' => ['privates', 'App\\Entity\\Fonction', 'getFonctionService', true],
        ], [
            'fonction' => 'App\\Entity\\Fonction',
        ]);
    }
}
