<?php

namespace ContainerGKpBONF;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_UShdoQ8Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.uShdoQ8' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.uShdoQ8'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'agent' => ['privates', 'App\\Entity\\Agent', 'getAgentService', true],
            'container' => ['services', 'service_container', 'getServiceContainerService', true],
            'filesystem' => ['privates', 'filesystem', 'getFilesystemService', true],
            'paginator' => ['services', 'knp_paginator', 'getKnpPaginatorService', true],
            'reader' => ['privates', 'PhpOffice\\PhpSpreadsheet\\Reader\\Xlsx', 'getXlsxService', true],
            'repoAgent' => ['privates', 'App\\Repository\\AgentRepository', 'getAgentRepositoryService', true],
            'repoIndem' => ['privates', 'App\\Repository\\IndemniteRepository', 'getIndemniteRepositoryService', true],
            'repoRemuneration' => ['privates', 'App\\Repository\\RemunerationRepository', 'getRemunerationRepositoryService', true],
        ], [
            'agent' => 'App\\Entity\\Agent',
            'container' => '?',
            'filesystem' => '?',
            'paginator' => '?',
            'reader' => 'PhpOffice\\PhpSpreadsheet\\Reader\\Xlsx',
            'repoAgent' => 'App\\Repository\\AgentRepository',
            'repoIndem' => 'App\\Repository\\IndemniteRepository',
            'repoRemuneration' => 'App\\Repository\\RemunerationRepository',
        ]);
    }
}
