<?php

namespace ContainerGKpBONF;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_QUBBp5Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.QUB_bp5' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.QUB_bp5'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'App\\Controller\\ConfigurationController::delete' => ['privates', '.service_locator.fX.XS9z', 'get_ServiceLocator_FX_XS9zService', true],
            'App\\Controller\\ConfigurationController::index' => ['privates', '.service_locator.wri7zfV', 'get_ServiceLocator_Wri7zfVService', true],
            'App\\Controller\\HomeController::agent' => ['privates', '.service_locator.uShdoQ8', 'get_ServiceLocator_UShdoQ8Service', true],
            'App\\Controller\\HomeController::agent_delete' => ['privates', '.service_locator.p2lktr1', 'get_ServiceLocator_P2lktr1Service', true],
            'App\\Controller\\HomeController::agent_liste_paiement' => ['privates', '.service_locator.sItm7Yu', 'get_ServiceLocator_SItm7YuService', true],
            'App\\Controller\\HomeController::agent_paiement' => ['privates', '.service_locator.JWtC6gJ', 'get_ServiceLocator_JWtC6gJService', true],
            'App\\Controller\\HomeController::home_agent__paiment_delete' => ['privates', '.service_locator.IlOB3wH', 'get_ServiceLocator_IlOB3wHService', true],
            'App\\Controller\\SecurityController::login' => ['privates', '.service_locator.rSTd.nA', 'get_ServiceLocator_RSTd_NAService', true],
            'App\\Kernel::loadRoutes' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'App\\Kernel::registerContainerConfiguration' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'kernel::loadRoutes' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'kernel::registerContainerConfiguration' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'App\\Controller\\ConfigurationController:delete' => ['privates', '.service_locator.fX.XS9z', 'get_ServiceLocator_FX_XS9zService', true],
            'App\\Controller\\ConfigurationController:index' => ['privates', '.service_locator.wri7zfV', 'get_ServiceLocator_Wri7zfVService', true],
            'App\\Controller\\HomeController:agent' => ['privates', '.service_locator.uShdoQ8', 'get_ServiceLocator_UShdoQ8Service', true],
            'App\\Controller\\HomeController:agent_delete' => ['privates', '.service_locator.p2lktr1', 'get_ServiceLocator_P2lktr1Service', true],
            'App\\Controller\\HomeController:agent_liste_paiement' => ['privates', '.service_locator.sItm7Yu', 'get_ServiceLocator_SItm7YuService', true],
            'App\\Controller\\HomeController:agent_paiement' => ['privates', '.service_locator.JWtC6gJ', 'get_ServiceLocator_JWtC6gJService', true],
            'App\\Controller\\HomeController:home_agent__paiment_delete' => ['privates', '.service_locator.IlOB3wH', 'get_ServiceLocator_IlOB3wHService', true],
            'App\\Controller\\SecurityController:login' => ['privates', '.service_locator.rSTd.nA', 'get_ServiceLocator_RSTd_NAService', true],
            'kernel:loadRoutes' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'kernel:registerContainerConfiguration' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
        ], [
            'App\\Controller\\ConfigurationController::delete' => '?',
            'App\\Controller\\ConfigurationController::index' => '?',
            'App\\Controller\\HomeController::agent' => '?',
            'App\\Controller\\HomeController::agent_delete' => '?',
            'App\\Controller\\HomeController::agent_liste_paiement' => '?',
            'App\\Controller\\HomeController::agent_paiement' => '?',
            'App\\Controller\\HomeController::home_agent__paiment_delete' => '?',
            'App\\Controller\\SecurityController::login' => '?',
            'App\\Kernel::loadRoutes' => '?',
            'App\\Kernel::registerContainerConfiguration' => '?',
            'kernel::loadRoutes' => '?',
            'kernel::registerContainerConfiguration' => '?',
            'App\\Controller\\ConfigurationController:delete' => '?',
            'App\\Controller\\ConfigurationController:index' => '?',
            'App\\Controller\\HomeController:agent' => '?',
            'App\\Controller\\HomeController:agent_delete' => '?',
            'App\\Controller\\HomeController:agent_liste_paiement' => '?',
            'App\\Controller\\HomeController:agent_paiement' => '?',
            'App\\Controller\\HomeController:home_agent__paiment_delete' => '?',
            'App\\Controller\\SecurityController:login' => '?',
            'kernel:loadRoutes' => '?',
            'kernel:registerContainerConfiguration' => '?',
        ]);
    }
}
