<?php

namespace ContainerGKpBONF;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getFonctionService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Entity\Fonction' shared autowired service.
     *
     * @return \App\Entity\Fonction
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Entity'.\DIRECTORY_SEPARATOR.'Fonction.php';

        return $container->privates['App\\Entity\\Fonction'] = new \App\Entity\Fonction();
    }
}
