<?php

namespace ContainerGKpBONF;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getPaieEventSubscriberService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Event\PaieEventSubscriber' shared autowired service.
     *
     * @return \App\Event\PaieEventSubscriber
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Event'.\DIRECTORY_SEPARATOR.'PaieEventSubscriber.php';

        return $container->privates['App\\Event\\PaieEventSubscriber'] = new \App\Event\PaieEventSubscriber(($container->privates['App\\Repository\\PaiementRepository'] ?? $container->load('getPaiementRepositoryService')));
    }
}
