<?php

namespace ContainerGKpBONF;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getXlsxService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'PhpOffice\PhpSpreadsheet\Reader\Xlsx' shared autowired service.
     *
     * @return \PhpOffice\PhpSpreadsheet\Reader\Xlsx
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'phpoffice'.\DIRECTORY_SEPARATOR.'phpspreadsheet'.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'PhpSpreadsheet'.\DIRECTORY_SEPARATOR.'Reader'.\DIRECTORY_SEPARATOR.'IReader.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'phpoffice'.\DIRECTORY_SEPARATOR.'phpspreadsheet'.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'PhpSpreadsheet'.\DIRECTORY_SEPARATOR.'Reader'.\DIRECTORY_SEPARATOR.'BaseReader.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'phpoffice'.\DIRECTORY_SEPARATOR.'phpspreadsheet'.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'PhpSpreadsheet'.\DIRECTORY_SEPARATOR.'Reader'.\DIRECTORY_SEPARATOR.'Xlsx.php';

        return $container->privates['PhpOffice\\PhpSpreadsheet\\Reader\\Xlsx'] = new \PhpOffice\PhpSpreadsheet\Reader\Xlsx();
    }
}
